public class exampleConn {
    String uname;
public String yas='khannnn';
 public List<String> items {get; set;}   
 
 public    exampleConn(){
       
       items = new List<String>();
       items.add('y');
       items.add('a');
       items.add('s');
       items.add('i');
       items.add('n');
      
 } 
    public String getUsername() {
        return uname;
    }
            
    public void sayHello() {
      
      //  uname = UserInfo.getName();
        uname =  uname;
        //return null;
    }
    
      
        
          
        
   
}